# Generated by Django 3.1 on 2021-05-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnbail',
            new_name='thumbnail',
        ),
    ]
