# Generated by Django 3.1 on 2021-05-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placce',
            new_name='place',
        ),
    ]
